// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovelMicroservice.Data;

#nullable disable

namespace NovelMicroservice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241208122355_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NovelMicroservice.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 3,
                            Name = "Fantasy"
                        },
                        new
                        {
                            CategoryID = 4,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("NovelMicroservice.Models.Chapter", b =>
                {
                    b.Property<int>("ChapterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ChapterID"));

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NovelID")
                        .HasColumnType("int");

                    b.HasKey("ChapterID");

                    b.HasIndex("NovelID");

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            ChapterID = 5,
                            ChapterNumber = 1,
                            Content = "Once upon a time...",
                            NovelID = 5
                        },
                        new
                        {
                            ChapterID = 6,
                            ChapterNumber = 1,
                            Content = "It was a dark and stormy night...",
                            NovelID = 6
                        });
                });

            modelBuilder.Entity("NovelMicroservice.Models.Novel", b =>
                {
                    b.Property<int>("NovelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NovelID"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NovelID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Novels");

                    b.HasData(
                        new
                        {
                            NovelID = 5,
                            Author = "Author A",
                            CategoryID = 3,
                            Description = "A fun tale for kids",
                            Name = "Little Adventures"
                        },
                        new
                        {
                            NovelID = 6,
                            Author = "Author B",
                            CategoryID = 4,
                            Description = "A scary story",
                            Name = "Haunted House"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
